name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  fmt:
    # cargo fmt
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo fmt
        run: cargo fmt --all -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo clippy
        run: cargo clippy --all -- -D warnings

  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo test
        run: cargo test  

