name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  fmt:
    # cargo fmt
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: cargo fmt
        run: cargo fmt

